name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' # Specify your Python version here

#    - name: Download artifact
#      uses: actions/download-artifact@v2
#      with:
#        name: pr-body

    - name: Extract project version and PR body
      id: update_info
      run: |
        VERSION=$(grep '__version__' src/tradinghours/__init__.py | cut -d '"' -f 2)
        echo "::set-output name=version::$VERSION"

#        PR_BODY=$(cat pr_body.txt)
#        echo "::set-output name=pr_body::$PR_BODY"

    - name: Build and publish package using Flit
      run: |
        pip install flit

        export FLIT_USERNAME=__token__
        export FLIT_PASSWORD=${{ secrets.PYPI_TOKEN }}

        flit publish

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ steps.update_info.outputs.version }}
        tag_name: ${{ steps.update_info.outputs.version }}
        body: |

#          ${{ steps.update_info.outputs.pr_body }}
  
