name: Python Version Testing

on:
  push:
    branches:
      - main
      - githubactions

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -e ".[dev]"

      - name: Run Tests
        run: python -m unittest discover -s tests
