name: Testing Release

on:
  pull_request:
    branches:
      - main

jobs:
  push_to_test_pypi:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.current_version.outputs.new_version }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Ensure this matches your project's Python version

      - name: get current version
        id: current_version
        run: |
          PYPI_VERSION=$(pip index versions tradinghours | cut -d'(' -f2 | cut -d')' -f1 | sed 1q)
          NEW_VERSION=$(grep '__version__' src/tradinghours/__init__.py | cut -d '"' -f 2)
          echo "comparing $NEW_VERSION with $PYPI_VERSION"
          if [[ $NEW_VERSION == $PYPI_VERSION ]]; then
            echo "Version needs to be incremented."
            exit 1
          fi
          
          echo "::set-output name=new_version::some data"
          
          DEV_VERSION=$NEW_VERSION.rc${{github.run_number}}.dev${{github.run_attempt}}
          echo "setting version to $DEV_VERSION"
          sed -i "s/$NEW_VERSION/$DEV_VERSION/" src/tradinghours/__init__.py

      - name: Install dependencies
        run: pip install flit pytest pytest-mock

      - name: release to test pypi
        run: |
          export FLIT_USERNAME=__token__
          export FLIT_PASSWORD=pypi-AgENdGVzdC5weXBpLm9yZwIkODQwMzhmMzctYjY4ZS00OGVkLThkZTMtYmU5NTIwNjJkMmEwAAIUWzEsWyJ0cmFkaW5naG91cnMiXV0AAixbMixbIjM4OTg2MjcyLWE1NDgtNGUwYy04YTM1LTIwMzM5YzMxNWRhZiJdXQAABiCtXltfnydrF_CsGbstHbS0V3Gka0tZ2QAhFlh-HrXKFw
          export FLIT_INDEX_URL=https://test.pypi.org/legacy
          flit publish

  test_from_test_pypi:
    needs: push_to_test_pypi
    runs-on: ubuntu-latest
    steps:
      - name: get from test pypi
        run: |
          NEW_VERSION=${{ needs.push_to_test_pypi.outputs.new_version }}
          DEV_VERSION=${NEW_VERSION}rc${{github.run_number}}.dev${{github.run_attempt}}
          echo "$DEV_VERSION"
          while [ "$DEV_VERSION" != "$(pip index versions -i https://test.pypi.org/simple --pre tradinghours | cut -d'(' -f2 | cut -d')' -f1 | sed 1q)" ];\
            do echo not found yet, sleeping 5s; sleep 5s; done
          pip install -i https://test.pypi.org/simple tradinghours==$DEV_VERSION

      - name: run tests
        run: |
          export TRADINGHOURS_TOKEN=${{ secrets.TEST_KEY }}

          tradinghours import
          tradinghours status --extended

          pytest 

      - name: Save PR body to a file
        run: echo "${{ github.event.pull_request.body }}" > pr_body.txt

      - name: Upload PR body as artifact
        uses: actions/upload-artifact@v2
        with:
          name: pr-body
          path: pr_body.txt